CREATE TABLE ADDRESS
(
    ADDRESS_ID BIGINT UNIQUE NOT NULL,
    DEPARTMENT_ADDRESS VARCHAR2(50) NOT NULL,
    ADDITIONAL_ADDRESS VARCHAR2(50) NULL,
    CITY VARCHAR2(50) NOT NULL,
    STATE VARCHAR2(2) NOT NULL,
    ZIP_CODE VARCHAR2(5) NOT NULL,
    CONSTRAINT ADDRESS_PK PRIMARY KEY (ADDRESS_ID)
);

CREATE TABLE DEPARTMENT
(
    DEPARTMENT_ID BIGINT UNIQUE NOT NULL,
    DEPARTMENT_NAME VARCHAR2(50) NOT NULL,
    DEPARTMENT_CODE VARCHAR(5) NOT NULL,
    PHONE VARCHAR2(12) NOT NULL,
    EMAIL VARCHAR2(64) NOT NULL,
    ADDRESS_ID BIGINT NOT NULL,
    CONSTRAINT DEPARTMENT_PK PRIMARY KEY (DEPARTMENT_ID),
    CONSTRAINT ADDRESS_FK FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID)
);

